name: Run Discord Bot 24/7

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
        
    - name: Run Discord Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python main.py
