name: Run Discord Bot 24/7

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Debug - See what files exist
      run: |
        echo "=== CURRENT DIRECTORY ==="
        pwd
        echo "=== LISTING ALL FILES ==="
        ls -la
        echo "=== LISTING SUBFOLDERS ==="
        find . -type f -name "*.py" | head -20
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install discord.py
        
    - name: Run Discord Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        echo "=== LOOKING FOR MAIN.PY ==="
        find . -name "main.py" -type f
        echo "=== RUNNING BOT ==="
        python main.py
