name: Run Discord Bot 24/7

on:
  workflow_dispatch:  # Allows manual trigger
  push:               # Run on code changes
    branches: [ main ]
  schedule:           # Restart every 6 hours to prevent issues
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max per run
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create config file
      run: |
        cat > config.py << EOL
        import os
        
        # Bot token from secrets
        BOT_TOKEN = os.getenv('BOT_TOKEN')
        
        # Bot prefix for commands
        BOT_PREFIX = "!"
        
        # Time limits for questions (in seconds)
        TIME_LIMITS = {
            "math": 90,
            "english": 45, 
            "analytical": 60,
            "puzzle": 300
        }
        
        # Mock test settings
        MOCK_TEST_CONFIG = {
            "math_count": 25,
            "english_count": 30,
            "analytical_count": 15,
            "time_limit": 3600
        }
        
        # Scoring system
        SCORING = {
            "correct": 1,
            "incorrect": -0.25
        }
        
        # Image folder paths
        IMAGE_PATHS = {
            "math": "./images/math/",
            "english": "./images/english/", 
            "analytical": "./images/analytical/"
        }
        
        # Math topics
        MATH_TOPICS = [
            "age", "average", "fraction", "interest", "number",
            "permutation", "profit-loss", "ratio", "solids", "triangle",
            "angle", "circle", "inequality", "mixture", "percentage",
            "probability", "quadrilateral", "set", "speed", "workdone"
        ]
        
        # English topics
        ENGLISH_TOPICS = [
            "analogy", "correct-use-of-word", "error-detection",
            "reading-comprehension", "rearrange", "sentence-completion",
            "sentence-correction", "suffix-prefix", "syn-ant"
        ]
        
        # Analytical topics
        ANALYTICAL_TOPICS = [
            "cr", "ds", "puzzle"
        ]
        EOL
        
    - name: Run Discord Bot
      env:
        BOT_TOKEN: \${{ secrets.BOT_TOKEN }}
      run: |
        python main.py